version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db/classpulse
      - SECRET_KEY=${SECRET_KEY:-default_key_change_me}
      - SOCKETIO_ASYNC_MODE=eventlet
    depends_on:
      - db
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
    command: gunicorn --workers=3 --bind=0.0.0.0:8000 --worker-class=eventlet 'wsgi:application'

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=classpulse
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: