version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-default_key_change_me}
      - SOCKETIO_ASYNC_MODE=threading
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped
    command: gunicorn --workers=4 --bind=0.0.0.0:5000 --worker-class=gthread --threads=2 'wsgi:application'