site_name: ClassPulse Documentation
site_description: Documentation for the ClassPulse real-time audience interaction tool
site_author: ClassPulse Team
repo_url: https://github.com/yourusername/classpulse
repo_name: yourusername/classpulse

nav:
  - Home: index.md
  - Getting Started: GETTING_STARTED.md
  - Architecture: ARCHITECTURE.md
  - Technical Specification: SPECIFICATION.md
  - Developer Guide: DEVELOPER_GUIDE.md
  - Data Flow: DATA_FLOW.md
  - API Reference: API_REFERENCE.md

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.critic
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/classpulse
